baseURL = 'https://example.org/'
defaultContentLanguage = 'nl'
title = 'La Grasse Matinée'
theme = 'ananke'

[params]
  text_color = "light-gray"
  author = ""
  favicon = ""
  site_logo = ""
  description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/profile.php?id=61556848555856"

[languages]
  [languages.en]
    disabled = false
    languageCode = 'en-GB'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'La Grasse Matinée'
    weight = 10
  [languages.nl]
    disabled = false
    languageCode = 'nl-BE'
    languageDirection = 'ltr'
    languageName = 'Nederlands'
    title = 'La Grasse Matinée'
    weight = 30
  [languages.fr]
    disabled = false
    languageCode = 'fr-FR'
    languageDirection = 'ltr'
    languageName = 'Français'
    title = 'La Grasse Matinée'
    weight = 20
    
[markup.goldmark.renderer]
unsafe= true